version: "3"

services:

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    env_file:
      - ./frontend/.env
    command: sh -c "npm run dev"